#!/usr/bin/env bash
## This script configures port forwarding from 8080 to 80 using ufw
#
## Flush existing rules to start fresh
iptables -t nat -F
iptables -t filter -F
#
## Port forwarding rule
iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
#
## Allow forwarding traffic on port 80
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp --sport 80 -j ACCEPT
#
## Save the rules
iptables-save > /etc/iptables/rules.v4
#
